issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: "ProviderServerWithResourceIdentity"
      linters:
      - SA1019

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - exportloopref
    - forcetypeassert
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - paralleltest
    - predeclared
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused