version: 2.1

commands:
  get_dependencies:
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go get -v -d ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  get_golangci_lint:
    steps:
      - run:
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.31.0
      - save_cache:
          key: golangci-lint-v1-31-0-{{ checksum "bin/golangci-lint" }}
          paths:
            - "bin/"

jobs:
  "docker-go117 build":
    docker:
      - image: circleci/golang:1.17
    steps:
      - get_dependencies
      - run: go build ./...
  "docker-go117 test":
    docker:
      - image: circleci/golang:1.17
        environment:
          TF_ACC_TERRAFORM_VERSION: "0.12.26"
    parameters:
      test_results:
        type: string
        default: /tmp/test-results
    steps:
      - get_dependencies
      - run: mkdir -p << parameters.test_results >>/report
      - run:
          command: |
            gotestsum --junitfile << parameters.test_results >>/report/gotestsum-report.xml -- -coverprofile=cover.out ./...
            go tool cover -html=cover.out -o coverage.html
            mv coverage.html << parameters.test_results >>
      - store_artifacts:
          path: << parameters.test_results >>
          destination: raw-test-output
      - store_test_results:
          path: << parameters.test_results >>
  "docker-go117 vet":
    docker:
      - image: circleci/golang:1.17
    steps:
      - get_dependencies
      - run: go vet ./...
  "docker-go117 gofmt":
    docker:
      - image: circleci/golang:1.17
    steps:
      - get_dependencies
      - run: ./scripts/gofmtcheck.sh
  "docker-go117 golangci-lint":
    docker:
      - image: circleci/golang:1.17
    steps:
      - get_dependencies
      - get_golangci_lint
      - run: bin/golangci-lint run -v ./...
  "docker-go117 release":
    docker:
      - image: circleci/golang:1.17
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e4:90:79:81:db:0f:b7:53:be:6e:58:81:40:34:47:1d"
      - get_dependencies
      - run: ./scripts/release/release.sh

workflows:
  version: 2
  pr:
    jobs:
      - "docker-go117 build"
      - "docker-go117 test":
          requires:
            - "docker-go117 build"
      - "docker-go117 vet":
          requires:
            - "docker-go117 build"
      - "docker-go117 gofmt":
          requires:
            - "docker-go117 build"
      - "docker-go117 golangci-lint":
          requires:
            - "docker-go117 build"
  release:
    jobs:
      - "docker-go117 build"
      - "docker-go117 test":
          requires:
            - "docker-go117 build"
      - "docker-go117 vet":
          requires:
            - "docker-go117 build"
      - "docker-go117 gofmt":
          requires:
            - "docker-go117 build"
      - "docker-go117 golangci-lint":
          requires:
            - "docker-go117 build"
      - trigger-release:
          filters:
            branches:
              only:
                - main
          type: approval
      - "docker-go117 release":
          filters:
            branches:
              only:
                - main
          requires:
            - trigger-release
            - "docker-go117 test"
            - "docker-go117 vet"
            - "docker-go117 gofmt"
            - "docker-go117 golangci-lint"
